use serde::{Deserialize, Serialize};

use crate::types::timestamp::Timestamp;

/// Metadata about the trace session and its environment.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TraceMetadata {
    pub tool: ToolInfo,
    pub trace_start: Timestamp,
    pub trace_end: Timestamp,
    pub target_process: ProcessInfo,
    pub host: HostInfo,
    pub generation_context: GenerationContext,
}

/// Identification of the tracing tool that produced the attestation.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolInfo {
    pub name: String,
    pub version: String,
}

/// Information about the process being traced.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProcessInfo {
    pub pid: u32,
    pub command: String,
    pub cgroup_id: u64,
}

/// Information about the host where the trace was collected.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct HostInfo {
    pub os: String,
    pub kernel_version: String,
    pub arch: String,
    /// Distribution codename sampled from `/etc/os-release`
    /// (`VERSION_CODENAME`), e.g. `bookworm`, `trixie`, `jammy`. Used as the
    /// `distro` qualifier when emitting deb PURLs. Absent on non-Debian-family
    /// systems or when `/etc/os-release` is unavailable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub distro_codename: Option<String>,
}

/// The context in which the attestation was generated. Propagates into
/// the CycloneDX `mikebom:generation-context` property so downstream
/// consumers can tell apart authoritative build-time observations from
/// lower-confidence post-hoc scans.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GenerationContext {
    /// Attestation generated from a build-time eBPF trace. Highest
    /// fidelity — every component is backed by a captured network or
    /// file event with evidence.
    #[serde(rename = "build-time-trace")]
    BuildTimeTrace,
    /// SBOM generated by walking a filesystem directory and matching
    /// known package-artifact path patterns. No eBPF; no attestation
    /// of the originating build. Confidence 0.70 per component.
    #[serde(rename = "filesystem-scan")]
    FilesystemScan,
    /// SBOM generated by extracting a container image's layers and
    /// scanning the resulting rootfs. Same machinery as filesystem
    /// scan, different subject.
    #[serde(rename = "container-image-scan")]
    ContainerImageScan,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generation_context_serializes_as_kebab() {
        let json =
            serde_json::to_string(&GenerationContext::BuildTimeTrace).expect("serialize context");
        assert_eq!(json, "\"build-time-trace\"");

        let back: GenerationContext =
            serde_json::from_str("\"build-time-trace\"").expect("deserialize context");
        assert_eq!(back, GenerationContext::BuildTimeTrace);
    }

    #[test]
    fn trace_metadata_serde_round_trip() {
        let meta = TraceMetadata {
            tool: ToolInfo {
                name: "mikebom".to_string(),
                version: "0.1.0".to_string(),
            },
            trace_start: Timestamp::now(),
            trace_end: Timestamp::now(),
            target_process: ProcessInfo {
                pid: 42,
                command: "cargo build".to_string(),
                cgroup_id: 12345,
            },
            host: HostInfo {
                os: "linux".to_string(),
                kernel_version: "6.5.0".to_string(),
                arch: "x86_64".to_string(),
                distro_codename: Some("bookworm".to_string()),
            },
            generation_context: GenerationContext::BuildTimeTrace,
        };

        let json = serde_json::to_string(&meta).expect("serialize metadata");
        let back: TraceMetadata = serde_json::from_str(&json).expect("deserialize metadata");
        assert_eq!(meta.tool.name, back.tool.name);
        assert_eq!(meta.host.arch, back.host.arch);
        assert_eq!(back.generation_context, GenerationContext::BuildTimeTrace);
    }
}
