#!/usr/bin/env bash
# Rust ecosystem demo.
#
# Traces `cargo fetch` for a tiny project that pulls in ripgrep's
# dependencies. We choose fetch (not `install` or `build`) because:
#   - `cargo install` spawns dozens of parallel rustc workers whose
#     burst of file opens overwhelms the eBPF ring buffer.
#   - fetch only does the HTTPS + file-write phase we actually need to
#     exercise for SBOM generation. The emitted trace is a clean record
#     of "what packages were pulled down for this build."
#
# Cargo uses rustls (not OpenSSL) for HTTPS, so our libssl uprobes do
# not fire on its traffic. Resolution is driven by the file-path side:
# every fetched crate lands at ~/.cargo/registry/cache/<index>/<name>-<ver>.crate,
# which `resolve::path_resolver::resolve_cargo_path` recognises.
set -euo pipefail

WORK="${OUT_DIR:-$(mktemp -d)}"
mkdir -p "$WORK"
echo "== rust demo ==" 1>&2
echo "workdir: $WORK" 1>&2

MIKEBOM="${MIKEBOM_BIN:-/mikebom/target/release/mikebom}"

PROJECT="$WORK/proj"
# Respect CARGO_HOME (Docker rust images default to /usr/local/cargo, not
# $HOME/.cargo). Wipe the cache so the fetch has to actually download and
# we can observe the network + file-write activity.
: "${CARGO_HOME:=$HOME/.cargo}"
CARGO_CACHE="$CARGO_HOME/registry/cache"
rm -rf "$PROJECT" "$CARGO_CACHE" "$CARGO_HOME/registry/src"
mkdir -p "$CARGO_CACHE"
cargo new --bin --quiet "$PROJECT"

# A small but meaningful transitive tree: ripgrep's core depends on
# regex, memchr, aho-corasick, and friends, and `tokio` pulls in a
# broader async stack. ~40 transitive crates total — non-trivial but
# small enough to observe cleanly.
cat > "$PROJECT/Cargo.toml" <<EOF
[package]
name = "mikebom-rust-demo"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.35", features = ["full"] }
anyhow = "1.0.79"
clap = { version = "4.4", features = ["derive"] }
EOF

echo ">> trace cargo fetch via mikebom" 1>&2
RUST_LOG=info "$MIKEBOM" trace run \
  --attestation-output "$WORK/mikebom.attestation.json" \
  --sbom-output        "$WORK/mikebom.cdx.json" \
  --trace-children \
  --skip-purl-validation \
  --no-enrich \
  --timeout 300 \
  --artifact-dir "$CARGO_CACHE" \
  -- bash -c "cd '$PROJECT' && cargo fetch --quiet"

# Cargo.lock is generated by cargo fetch — our ground truth for recall.
cp "$PROJECT/Cargo.lock" "$WORK/Cargo.lock"

echo ">> syft scan of cargo cache" 1>&2
syft "dir:$CARGO_CACHE" -o cyclonedx-json="$WORK/syft.cdx.json" -q || {
  echo "!! syft failed" 1>&2; exit 3;
}

echo ">> trivy scan of cargo cache" 1>&2
trivy fs --format cyclonedx --output "$WORK/trivy.cdx.json" --quiet "$CARGO_CACHE" || {
  echo "!! trivy failed" 1>&2; exit 4;
}

echo ">> compare" 1>&2
"$MIKEBOM" sbom compare \
  --mikebom "$WORK/mikebom.cdx.json" \
  --syft    "$WORK/syft.cdx.json" \
  --trivy   "$WORK/trivy.cdx.json" \
  --truth   "$WORK/Cargo.lock" \
  --ecosystem cargo \
  --output  "$WORK/report.md" \
  --json

echo "== report =="
cat "$WORK/report.md"
